### ISSUE TITLE
Two PSP datasets have the same DOI value

### ISSUE THREAD

**Issue by berniegsfc** [hpde/NASA#3]
The following two PSP NumericalData description have the same DOI value (https://doi.org/10.48322/2nwb-7q79):

- https://hpde.io/NASA/NumericalData/ParkerSolarProbe/FIELDS/DFB/Level2/AC/Spectra/SCM/U/LowFrequency/HighGain/PT0.873813S.xml
- https://hpde.io/NASA/NumericalData/ParkerSolarProbe/FIELDS/DFB/Level2/AC/Spectra/SCM/F/LowFrequency/HighGain/PT0.873813S.xml

**Comment by lfb12345** [comment]
Hi Bernie, I finally fixed this issue. Thanks much!

**Comment by lfb12345** [comment]
Issue Closed LFB 20220815
