### ISSUE TITLE
Wrong AccessURL/Name for spase://NASA/NumericalData/Wind/3DP/ECHSFITS_E0-DAY/PT96S

### ISSUE THREAD

**Issue by berniegsfc** [hpde/NASA#5]
`spase://NASA/NumericalData/Wind/3DP/ECHSFITS_E0-DAY/PT96S` has
```
<AccessURL>
<Name>CDAWeb</Name>
```
but the rest of the AccessInformation indicates that this is an SPDF dataset and not available through CDAWeb.  If this is not a cdaweb dataset, the name should be changed to, by convention, `HTTPS from SPDF`.  There exists software that expects an `//AccessURL/Name` of `CDAWeb` to indicate that the data is available from cdaweb.
`spase://NASA/NumericalData/Wind/3DP/ECHSFITS_E0-YR/PT96S` has the same problem.

**Comment by faith610** [comment]
Bernie, I'm in the SMWT meeting right now.  I have also noticed that:

<AccessURL>
<Name>CDAWeb</Name>
<URL>https://spdf.gsfc.nasa.gov/pub/data/wind/3dp/3dp_echsfits_e0-day/</URL>
<ProductKey>wind_3dp_echsfits_e0-**day**</ProductKey>
<Description>In CDF via HTTP from SPDF</Description>
</AccessURL>

< URL> and <ProductKey> are wrong for the "wind-3dp-echsfits_e0-yr". The example I have above is for YR and everything was referenced to "day".  I have mentioned to the group and Scott is going to change it.

**Comment by faith610** [comment]
https://cdaweb.gsfc.nasa.gov/registry/hdp/Spase.xql?id=spase://NASA/NumericalData/Wind/3DP/ECHSFITS_E0-YR/PT96S

**Comment by tressahelvey** [comment]
Hello Scott, Do you recall fixing this issue? (from last May?)  If so, are we able to close this ticket? Thank you. Tressa
