### ISSUE TITLE
Missing AccessURL/Name for spase://NASA/NumericalData/SOHO/CELIAS/PT30S

### ISSUE THREAD

**Issue by berniegsfc** [hpde/NASA#6]
The AccessURL/Name is missing for spase://NASA/NumericalData/SOHO/CELIAS/PT30S
This results in nothing appearing in the `Data Access` box on [hpde.io page](https://hpde.io//NASA/NumericalData/SOHO/CELIAS/PT30S).

**Comment by tressahelvey** [comment]
Chuck, can you see why this access url is not showing on Data Access box on  hdpe.io   https://l1.umd.edu/

**Comment by berniegsfc** [comment]
Wasn't this "fixed" by [commit b0ec3ad](https://github.com/spase-group/spase-generate-pages/commit/b0ec3ade7ac3a1a65e8ce2c12597cd8be21cc455)?

**Comment by cfdolan** [comment]
There's no Name field set in the AccessURL element, so there's nothing to work with there. Commit b0ec3ad dealt with the file format, not the name.
![image](https://github.com/hpde/NASA/assets/6527863/879f1214-6b12-4faa-9545-d2961a741efd)

**Comment by berniegsfc** [comment]
Before commit b0ec3ad, nothing appeared in the `Data Access` box.  Now `Text` appears and it links to the AccessURL/URL which is better than nothing.  My comment had `fixed` in quotations because it's not as good has it would be with a Name element, but it's better than before.

**Comment by tressahelvey** [comment]
Hello, the "text" link opens the url: https://l1.umd.edu/ which is in the SPASE record (see above). Do we not want to include that url in the access info box?  If we do want it shown, does it need to be in a different field? I was looking at the schema and do not see a "name" field under AccessInformation.  
Thank you

**Comment by berniegsfc** [comment]
Attached is what you'll get if
```
<Name>Proton Monitor Data</Name>
```
is added.
<img width="985" alt="Screenshot 2024-02-01 at 9 15 38 AM" src="https://github.com/hpde/NASA/assets/22496475/be2e2236-1632-4041-aeb3-48e67ee87645">
